@baseurl = http://127.0.0.1:5501
# @baseurl = https://realityshift-sber.rtuitlab.ru

GET {{baseurl}}/api/modules/


###
GET {{baseurl}}/api/modules/1

###
POST {{baseurl}}/api/modules/
Content-Type: application/json

{
    "title": "new Title"
}

###

PUT {{baseurl}}/api/modules/2
Content-Type: application/json

{
    "title": "edited Title"
}

###
GET {{baseurl}}/api/modules/1/general

###
PUT {{baseurl}}/api/modules/1/general
Content-Type: application/json

{
    "Visibility": 1,
    "ClassLevel": 6,
    "Course": "Математика",
    "LaborIntensity":1.6,
    "Tags": [
        "Tag1", "Another"
    ],
    "BasicIdea": "Sime basic data",
    "ProblemQuestion": "Some problem description"
}

###
GET {{baseurl}}/api/modules/1/teacherInstructions

###
PUT {{baseurl}}/api/modules/1/teacherInstructions
Content-Type: application/json

{
  "generalMeaning": "Meaning",
  "exercisesByLessons": "by lesson",
  "challenges": "challenges"
}